aplikacja_szik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('comparison/', include('comparison.urls')),
    path('admin/', admin.site.urls),
    path('files/', include('db_file_storage.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comparison/urls.py
from django.urls import path

from comparison import views


app_name = 'comparison'


urlpatterns = [

    path('<int:category_id>/', views.index, name='index'),

    path('add/<int:product_id>/', views.add, name='add'),

    path('remove/<int:product_id>/', views.remove, name='remove'),

    path('toggle/<int:product_id>/', views.toggle, name='toggle')

]

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views
from .views import (
    ProductView,
    OrderSummaryView,
    CheckoutView,
    ShopsView,
    home_view,
    sales_view,
    search_products,
    get_nearest_shop,
    add_to_cart,
    remove_from_cart,
    reduce_quantity_item,
    activate,
)

app_name = 'pages'

urlpatterns = [
    path('', home_view, name='home'),
    path('home/', home_view, name='home'),
    path('about/', views.about, name='about'),
    # sklepy
    path('shops', ShopsView.as_view(), name='shops'),
    path('get-nearest-shop/<str:lat>/<str:lng>/', get_nearest_shop, name='get-nearest-shop'),
    # produkty
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('sales', sales_view, name='sales'),
    path('search-products', search_products, name='search-products'),
    # koszyk
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    # zamówienia
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    # rejestracja
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerView, name='register'),
    path('contact/', views.contact, name='contact'),
    path('search-points', views.search_points, name='search-points'),
    path('orders_list/', views.users_orders_list, name='orders_list'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('update_profile/', views.update_profileView, name='update_profile'),
]

pages/templates/pages/base.html
{% load static %}
{% load pwa %}
{% load fontawesome_5 %}
{% load comparison_tags %}

{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Aplikacja e-commerce</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'pages/favicon.ico' %}"/>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>

    {% progressive_web_app_meta %}
    {% fontawesome_5_static %}
</head>

<body>

<!-- Navbar -->
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark main-navbar scrolling-navbar mb-4">
    <div class="container-fluid" id="nav-container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <div style="width: 120px; height: 60px;">
                <img src="{% static 'img/logo.png' %}" width="100%" height="100%" alt="logo">
            </div>
        </a>

        <!-- Collapse -->
        <button id="nb-toggle" class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav" id="nav-links">
                {% url 'pages:home' as home %}
                {% url 'pages:sales' as sales %}
                {% url 'pages:shops' as shops %}
                {% url 'pages:contact' as contact %}

                <li {% if request.path == home %}class="nav-item mx-2 active"
                    {% else %}class="nav-item mx-2"{% endif %}>
                    <a class="nav-link" href="{{ home }}">Oferta</a>
                </li>

                <li {% if request.path == sales %}class="nav-item mx-2 active"
                    {% else %}class="nav-item mx-2"{% endif %}>
                    <a class="nav-link" href="{{ sales }}">Promocje</a>
                </li>

                <li {% if request.path == shops %}class="nav-item mx-2 active"
                    {% else %}class="nav-item mx-2"{% endif %}>
                    <a class="nav-link" href="{{ shops }}">Nasze placówki</a>
                </li>

                <li {% if request.path == contact %}class="nav-item mx-2 active"
                    {% else %}class="nav-item mx-2"{% endif %}>
                    <a class="nav-link" href="{{ contact }}">Kontakt</a>
                </li>
            </ul>

            <br/>

            <!-- Search -->
            <div class="navbar-nav mx-auto">
                <form class="form-inline" method="POST" action={% url 'pages:search-products' %}>

                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" id="search-inp" type="text" placeholder="Szukaj" aria-label="Szukaj"
                               name="searched">
                    </div>
                    <div class="form-group-append">
                        <button class="btn yellow-btn search-btn" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>

                </form>
            </div>

            {% include 'comparison/dropdown.html' %}


            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                <!-- Cart -->
                {% if user.is_authenticated %}
                    <li class="nav-item mx-1">
                        <a href="{% url 'pages:order-summary' %}" class="nav-link waves-effect">
                            {% if request.user|cart_item_count != 0 %}
                                <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                            {% endif %}
                            <i class="fas fa-shopping-cart"></i>
                            <span class="disappear"> Koszyk </span>
                        </a>
                    </li>

                    <!-- User account -->
                    <li class="nav-item dropdown mx-1">
                        <a class="nav-link waves-effect" data-toggle="dropdown">
                            <i class="fas fa-user"></i><span class="disappear">{{ user.username }}</span>
                            <i class="fas fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu" id="account-dropdown">
                            {% if user.is_staff %}
                                <li><a class="dropdown-item pl-4" href="{% url 'admin:index' %}">Panel
                                    administratora</a></li>
                            {% endif %}
                            <li><a class="dropdown-item pl-4" href="{% url 'pages:update_profile' %}">Moje konto</a>
                            </li>
                            <li><a class="dropdown-item pl-4" href="{% url 'pages:orders_list' %}">Zamówienia</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item pl-4" href="{% url 'pages:logout' %}">
                                <i class="fas fa-power-off"></i> Wyloguj się
                            </a></li>
                        </ul>
                    </li>
                {% else %}

                    <!-- Login -->
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'pages:register' %}">Zarejestruj się</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'pages:login' %}">Zaloguj</a>
                    </li>
                {% endif %}

            </ul>

        </div>

    </div>
</nav>

<!-- Page content -->
<div class="container-fluid" style="min-height: calc(100vh - 240px);">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock content %}

</div>
<!-- Page content end -->

{% include 'pages/footer.html' %}

{% include 'pages/scripts.html' %}

{% block extra_scripts %}
{% endblock extra_scripts %}

</body>

</html>

pages/templates/pages/checkout.html
{% extends 'pages/base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

    <main>
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Dostawa i płatność</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!--Card content-->
                        <form method="POST" class="card-body">
                            {% csrf_token %}
                            <!--address-->
                            <div class="md-form mb-5">
                                {{ form.street_address }}
                                <label for="address" class="">Adres</label>
                            </div>

                            <!--address-2-->
                            <div class="md-form mb-5">
                                {{ form.apartment_address }}
                                <label for="address-2" class="">Adres cd.</label>
                            </div>

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <label for="country">Kraj</label>
                                    {{ form.country }}
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip_code">Kod pocztowy</label>
                                    {{ form.zip_code }}
                                    <div class="invalid-feedback">
                                        Kod pocztowy jest wymagany.
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <hr>

                            <div id="payment_option_div" class="d-block my-3">
                                <label for="payment_option_div">Sposób płatności</label>
                                {% for value, name in form.fields.payment_option.choices %}
                                    <div class="custom-control custom-radio">
                                        <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                                               class="custom-control-input" required>
                                        <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                                    </div>
                                {% endfor %}
                            </div>

                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Zapłać</button>

                        </form>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">

                    <!-- Heading -->
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Zawartość zamówienia</span>
                        <span class="badge badge-secondary badge-pill">{{ order.order_lines.count }}</span>
                    </h4>

                    <!-- Cart -->
                    <ul class="list-group mb-3 z-depth-1">

                        {% for order_item in order.order_lines.all %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div class="text-break text-wrap">
                                    {{ order_item.quantity }} x {{ order_item.product.name }}
                                </div>
                                <span class="text-muted">{{ order_item.get_final_price }}&nbsp;zł</span>
                            </li>
                        {% endfor %}

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Łączna cena: </span><strong>{{ order.get_total_price }}&nbsp;zł</strong>
                        </li>
                    </ul>
                    <!-- Cart -->

                </div>

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->

{% endblock content %}

pages/templates/pages/contact.html
{% extends 'pages/base.html' %}


{% block content %}
    <div class="container dark-grey-text">
        <div class="my-5 text-center"><h1 class="font-weight-bold">Kontakt z naszymi placówkami</h1></div>

        <nav class="navbar navbar-expand-lg navbar-dark nav-category mb-5">

            <div class="collapse navbar-collapse" id="basicExampleNav">
                <span class="navbar-brand">Znajdź placówkę</span>
            </div>

            <form class="form-inline" method="POST" action={% url 'pages:search-points' %}>
                {% csrf_token %}
                <div class="md-form my-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Wpisz miasto" aria-label="Szukaj"
                           name="searched">
                    <button class="btn yellow-btn" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>

        </nav>

        {% for point in szik_points %}
            <hr>
            <div class="mt-5">
                <h2 class="d-inline-block">{{ point.city }} {{ point.postal_code }} {{ point.street_address }}</h2>
                <p class="ml-3 d-inline-block" style="font-size: 20px">telefon: {{ point.telephone }}</p>
            </div>

            <div class="mt-1">

                <div class="col-lg-6 mb-4 text-center">
                    <div class="card product-card">
                        <div class="card-body">
                            {% if point.photo %}
                                <img src="{{ point.photo.url }}" class="img-fluid product-img" alt="">
                            {% else %}
                                <img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/No-image-available.png"
                                     class="img-fluid" alt="">
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>

{% endblock %}

pages/templates/pages/login.html
{% extends 'pages/base.html' %}

{% block content %}
    {% load static %}

    <style>
        .form-inp {
            width: 300px;
        }

        .form-group {
            position: relative;
            margin-bottom: 15px
        }

        .form-control {
            width: 100%;
            height: 50px;
            border: none;
            padding: 5px 7px 5px 15px;
            background: #fff;
            color: #666;
            border: 2px solid #ddd
        }

        .form-group .mdi {
            position: absolute;
            right: 15px;
            top: 17px;
            color: #999
        }

        .mdi {
            top: 13px !important;
            color: #404040 !important
        }

        .alert {
            font-size: 15px;
            color: #f00;
            text-align: center;
        }
    </style>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css">

    <main class="container">

        <div class="col-lg-6 d-flex card mx-auto text-center" style="background-color: #353535; color:white">
            <h3 class="card-title p-2 mt-2 font-weight-bold" style="color: #FFEA09;">Zaloguj się</h3>

            {% if invalid_login %}
                <p class="alert alert-danger">
                    Niepoprawny login lub hasło. Spróbuj ponownie.
                </p>
            {% endif %}

            <div class="d-flex card-body login-form justify-content-center">

                <form id="login-form" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <input id="username" name="username" type="text" class="form-control form-inp"
                               placeholder="Login">
                        <i class="mdi mdi-account"></i>
                    </div>

                    <div class="form-group">
                        <input id="password" name="password" type="password" class="form-control form-inp"
                               placeholder="Hasło">
                        <i class="mdi mdi-lock"></i>
                    </div>

                    <button type="submit" class="btn yellow-btn mt-3">Zaloguj się</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>

            </div>

            <p class="card-text mb-3">Nie masz konta?
                <a href="{% url 'pages:register' %}" style="color: #fdf383">Zarejestruj się</a>
            </p>

        </div>

    </main>

{% endblock content %}

pages/templates/pages/orders_list.html
{% extends 'pages/base.html' %}


{% block content %}
    <div class="container dark-grey-text text-break text-wrap mt-5"><h1>Historia zamówień</h1>
        {% for order in orders_list %}
            <div class="container dark-grey-text mt-5">
                <h2>{{ order.order_date }}</h2>
            </div>
            <div class="container dark-grey-text mt-1"><p>
                <table class="table table-dark table-striped">
                    <tr>
                        <th>Produkt</th>
                        <th>Ilość</th>
                        <th>Cena za sztukę</th>
                        <th>Cena łącznie</th>
                    </tr>
                    {% for o in order.order_lines.all %}
                        <tr>
                            <td>{{ o.product.name }}</td>
                            <td>{{ o.quantity }}</td>

                            <td>{% if o.product.discount is None %}
                                {{ o.product.price }} zł
                            {% else %}
                                {{ o.product.get_discount_price }} zł
                            {% endif %}</td>
                            <td>{{ o.get_final_price }} zł</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="container dark-grey-text mt-1">
                Łączna kwota: {{ order.get_total_price }} zł
                <br />
                Metoda płatności: {{ order.payment_method }}
                <br />
                <!-- Invoice download -->
                {% if order.invoice_file %}
                    <a href="{% url "db_file_storage.download_file" %}?name={{ order.invoice_file }}">
                        <button class="btn yellow-btn download-btn">
                            Pobierz fakturę <i class="fas fa-file-pdf"></i>
                        </button>
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>


{% endblock %}

pages/templates/pages/product_card.html
<div class="card h-100">
    <!--Card image-->
    <div class="view overlay product-list-img d-flex align-items-center">
        {% if item.image %}
            <img src="{% url 'db_file_storage.get_file' %}?name={{ item.image }}" class="img-fluid card-img-top" alt="">
        {% else %}
            <img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/No-image-available.png" class="card-img-top"
                 alt="">
        {% endif %}
        <a href="{{ item.get_absolute_url }}">
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>
    <!--Card image-->
    <!--Card content-->
    <div class="card-body text-center">
        <!--Category & Title-->
        {% if not hide_category_on_product_cards %}
            <a href="{{ item.category.get_absolute_url }}" class="grey-text">
                {{ item.get_category_display }}
            </a>
            <br>
        {% endif %}
        <strong>
            <a href="{{ item.get_absolute_url }}" class="dark-grey-text text-break text-wrap">{{ item.name }}</a>
        </strong>

        <h5 class="font-weight-bold blue-text">
            <strong>
                {% if item.discount %}
                    <span class="mr-1"><del>{{ item.price }} zł</del></span>
                    <span>{{ item.get_discount_price }} zł</span>
                {% else %}
                    <span>{{ item.price }} zł</span>
                {% endif %}
            </strong>
        </h5>
    </div>
    <!--Card content-->

</div>

pages/templates/pages/register.html
{% extends 'pages/base.html' %}

{% block content %}

    <style>
        .form-inp {
            width: 300px;
        }

        .form-group {
            position: relative;
            margin-bottom: 15px
        }

        .form-control {
            width: 100%;
            height: 50px;
            border: none;
            padding: 5px 7px 5px 15px;
            background: #fff;
            color: #666;
            border: 2px solid #ddd
        }

        .form-group .mdi {
            position: absolute;
            right: 15px;
            top: 17px;
            color: #999
        }

        .mdi {
            top: 13px !important;
            color: #404040 !important
        }

        .alert {
            font-size: 15px;
            color: #f00;
            text-align: center;
        }
    </style>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css">

    <main class="container">
        <div class="col-lg-6 d-flex card mx-auto text-center" style="background-color: #353535; color:white">
            <h3 class="card-title p-2 mt-2 font-weight-bold" style="color: #FFEA09;">Zarejestruj się</h3>
            <div class="d-flex card-body login-form justify-content-center">

                <form id="login-form" method="post">{% csrf_token %}{% load widget_tweaks %}

                    <div class="form-group">
                        {{ form.username | add_class:"form-control" }} <i class="mdi mdi-account"></i>
                    </div>
                    <div class="form-group log-status">
                        {{ form.email | add_class:"form-control" }} <i class="mdi mdi-email"></i>
                    </div>
                    <div class="form-group log-status">
                        {{ form_prof.user_type | add_class:"form-control" }}
                    </div>
                    <div class="form-group log-status">
                        {{ form.password1 | add_class:"form-control" }} <i class="mdi mdi-lock"></i>
                    </div>
                    <div class="form-group log-status">
                        {{ form.password2 | add_class:"form-control" }} <i class="mdi mdi-lock"></i>
                    </div>

                    {% if form.errors %}
                        <p class="d-block mt-3">Rejestracja nie powiodła się: </p>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <button type="submit" class="btn yellow-btn mt-3">Zarejestruj się</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>

            </div>

            <p class="card-text mb-3">Masz już konto?
                <a href="{% url 'pages:login' %}" style="color: #fdf383">Zaloguj się</a>
            </p>

        </div>
    </main>

{% endblock content %}

pages/templates/pages/sales.html
{% extends 'pages/base.html' %}

{% block content %}

    <div class="container justify-content-center text-center my-4">
        <div class="jumbotron px-3 py-3 mx-auto" style="background-color: #363636; color: #FFEA09; width: 75%">
            <h3>% % %</h3>
            <h1 style="font-weight: bold; color: white">Aktualne promocje w naszym sklepie</h1>
            <h3>% % %</h3>
        </div>
    </div>

    {% include "pages/product_list.html" %}

{% endblock content %}

pages/templates/pages/scripts.html
{% load static %}

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>


<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>

<!-- Skrypty -->
<script type="text/javascript" src="{% static 'js/main/shopping-cart.js' %}"></script>
<script type="text/javascript" src="{% static 'comparison/comparison.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main/main.js' %}"></script>

pages/templates/pages/search_points.html
{% extends 'pages/base.html' %}


{% block content %}
    <div class="container dark-grey-text">
        <div class="my-5 text-center"><h1 class="font-weight-bold">Kontakt z naszymi placówkami</h1></div>

        <nav class="navbar navbar-expand-lg navbar-dark nav-category mb-5">

            <div class="collapse navbar-collapse" id="basicExampleNav">
                <span class="navbar-brand">Znajdź placówkę</span>
            </div>

            <form class="form-inline" method="POST" action={% url 'pages:search-points' %}>
                {% csrf_token %}
                <div class="md-form my-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Wpisz miasto" aria-label="Szukaj"
                           name="searched">
                    <button class="btn yellow-btn" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>

        </nav>

        {% if searched %}
            <div class="container dark-grey-text mt-1">
                <h2> Wyniki wyszukiwania dla {{ searched }}:</h2>
            </div>
        {% endif %}

        {% if szik_points %}
        {% else %}
            <div class="container dark-grey-text mt-1">
                <h2> Nie mamy placówki w podanej lokalizacji</h2>
            </div>
        {% endif %}

        {% for point in szik_points %}
            <hr>
            <div class="mt-5">
                <h2 class="d-inline-block">{{ point.city }} {{ point.postal_code }} {{ point.street_address }}</h2>
                <p class="ml-3 d-inline-block" style="font-size: 20px">telefon: {{ point.telephone }}</p>
            </div>

            <div class="mt-1">

                <div class="col-lg-6 mb-4 text-center">
                    <div class="card product-card">
                        <div class="card-body">
                            {% if point.photo %}
                                <img src="{{ point.photo.url }}" class="img-fluid product-img" alt="">
                            {% else %}
                                <img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/No-image-available.png"
                                     class="img-fluid" alt="">
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>

{% endblock %}