aplikacja_szik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('comparison/', include('comparison.urls')),
    path('admin/', admin.site.urls),
    path('files/', include('db_file_storage.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comparison/urls.py
from django.urls import path

from comparison import views


app_name = 'comparison'


urlpatterns = [

    path('<int:category_id>/', views.index, name='index'),

    path('add/<int:product_id>/', views.add, name='add'),

    path('remove/<int:product_id>/', views.remove, name='remove'),

    path('toggle/<int:product_id>/', views.toggle, name='toggle')

]

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views
from .views import (
    ProductView,
    OrderSummaryView,
    CheckoutView,
    ShopsView,
    home_view,
    sales_view,
    search_products,
    get_nearest_shop,
    add_to_cart,
    remove_from_cart,
    reduce_quantity_item,
    activate,
)

app_name = 'pages'

urlpatterns = [
    path('', home_view, name='home'),
    path('home/', home_view, name='home'),
    path('about/', views.about, name='about'),
    # sklepy
    path('shops', ShopsView.as_view(), name='shops'),
    path('get-nearest-shop/<str:lat>/<str:lng>/', get_nearest_shop, name='get-nearest-shop'),
    # produkty
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('sales', sales_view, name='sales'),
    path('search-products', search_products, name='search-products'),
    # koszyk
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    # zamówienia
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    # rejestracja
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerView, name='register'),
    path('contact/', views.contact, name='contact'),
    path('search-points', views.search_points, name='search-points'),
    path('orders_list/', views.users_orders_list, name='orders_list'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('update_profile/', views.update_profileView, name='update_profile'),
]

comparison/views.py
from django.apps import apps
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.http.response import JsonResponse
from django.template.loader import render_to_string

from comparison.config import COMPARISON_CATEGORY_MODEL
from collections import defaultdict


def prepare_attributes(products):
    all_attributes = set()
    for product in products:
        if product.attributes:
            for key, value in dict(product.attributes).items():
                all_attributes.add(key)

    attribute_map = defaultdict(list)
    for attribute in all_attributes:
        for count, product in enumerate(products):
            if product.attributes and attribute in product.attributes:
                attribute_map[attribute].append(str(product.attributes[attribute]))
            else:
                attribute_map[attribute].append('-')
    return dict(attribute_map)


def index(request, category_id):
    category_model = apps.get_model(COMPARISON_CATEGORY_MODEL)

    category = get_object_or_404(category_model, id=category_id)

    products = request.comparison.get_products(category_id)

    context = {
        'category': category,
        'products': products,
        'attributes': prepare_attributes(products)
    }

    return render(request, 'comparison/index.html', context)


@require_POST
@csrf_exempt
def toggle(request, product_id):

    if request.comparison.has_product(product_id):
        return remove(request, product_id)

    return add(request, product_id)


@require_POST
@csrf_exempt
def add(request, product_id):
    return _action_view(
        request,
        product_id,
        action=lambda p: request.comparison.add(p),
        message=lambda p: 'Przedmiot {} dodany do porównania'.format(p.name))


@require_POST
@csrf_exempt
def remove(request, product_id):
    return _action_view(
        request,
        product_id,
        action=lambda p: request.comparison.remove(p),
        message=lambda p: 'Przedmiot {} usunięty z porównania'.format(p.name))


def _action_view(request, product_id, action, message):

    product = get_object_or_404(
        apps.get_model('pages', 'Product'), id=product_id)

    action(product)

    if not request.is_ajax():
        return redirect(request.POST.get('next', 'home'))

    return JsonResponse({
        'message': message(product),
        'dropdown': render_to_string(
            'comparison/dropdown.html', request=request),
        'is_active': request.comparison.has_product(product_id)
    })

comparison/templates/comparison/dropdown.html
{% load i18n %}
{% load fontawesome_5 %}

<div class="nav-item dropdown">
    <a href="javascript:void(0);"
       id="comparison-dropdown"
       data-role="comparison-dropdown"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false"
       class="nav-link waves-effect"
       {% if request.comparison.is_empty %}
           style="visibility:hidden"
       {% endif %}
    >

        {% if not request.comparison.is_empty %}
            <span class="badge red z-depth-1 mr-1">{{ request.comparison|length }}</span>
            {% fa5_icon 'balance-scale-right' color='white' %}<span style="color:white">Porównanie</span>
        {% endif %}
    </a>

    {% if not request.comparison.is_empty %}
        <ul class="dropdown-menu" aria-labelledby="comparison-dropdown">
            {% for category in request.comparison.get_categories %}
                <li>
                    <a href="{% url 'comparison:index' category.id %}">
                        {{ category.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

comparison/templates/comparison/index.html
{% extends 'pages/base.html' %}

{% load i18n %}

{% block content %}

    {% if products %}
        <style>
            .comparsion-product-img {
            max-height: 200px;
            width: auto;
            margin-left: auto;
            margin-right: auto;
            }

            .product-card {
                height: 225px;
                width: 275px;
            }
        </style>

        <div class="container">

            <h2>
                Porównanie produktów z kategorii {{ category.name }}
            </h2>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tbody>

                        <tr>
                            <td>
                                Zdjęcie
                            </td>

                            {% for product in products %}
                                <td>
                                    <a href="{{ product.get_absolute_url }}">
                                        {% block product_logo %}
                                            <div class="card product-card p-3">
                                            {% if product.image %}
                                                <img src="{% url 'db_file_storage.get_file' %}?name={{ product.image }}" class="img-fluid h-100 comparsion-product-img" alt="{{ product.name }}">
                                            {% else %}
                                                <img src="https://upload.wikimedia.org/wikipedia/commons/0/0a/No-image-available.png" class="img-fluid comparsion-product-img" alt="{{ product.name }}">
                                            {% endif %}
                                            </div>
                                        {% endblock %}
                                    </a>
                                </td>
                            {% endfor %}
                        </tr>

                        <tr>
                            <td>
                                Nazwa produktu
                            </td>

                            {% for product in products %}
                                <td>
                                    {% block product_name %}
                                        <a href="{{ product.get_absolute_url }}">
                                            {{ product.name }}
                                        </a>
                                    {% endblock %}
                                </td>
                            {% endfor %}
                        </tr>

                        <tr>
                            <td>
                                Działania
                            </td>

                            {% for product in products %}
                                <td>
                                    {% block actions %}
                                        <form method="post"
                                              action="{% url 'comparison:remove' product.id  %}"
                                              class="pull-left">
                                            <input type="hidden" name="next" value="{{ request.get_full_path }}">

                                            <button type="submit"
                                                    class="btn btn-danger btn-md m-r-10"
                                                    title="Usuń produkt z porównania">
                                                    Usuń z porównania
                                            </button>
                                        </form>
                                    {% endblock %}
                                </td>
                            {% endfor %}
                        </tr>

                        <tr>
                            <td>
                                Cena
                            </td>

                            {% for product in products %}
                                <td>
                                    {% block product_price %}
                                        <b>{{ product.get_discount_price }} zł</b>
                                    {% endblock %}
                                </td>
                            {% endfor %}
                        </tr>

                        {% block attributes %}
                            {% for name, list in attributes.items %}
                                <tr>
                                    <td>
                                        {{ name }}
                                    </td>

                                    {% for value in list %}
                                        <td>{{ value }}</td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        {% endblock %}

                    </tbody>
                </table>
            </div>

        </div>
    {% else %}
        <div class="container alert alert-info">
            Nie znaleziono produktów.
            <a href="{% url 'pages:home' %}">
                Wróć do strony głównej
            </a>
        </div>
    {% endif %}
{% endblock %}

comparison/templates/comparison/toggle_button.html
{% load i18n comparison_tags %}


<button data-url="{% url 'comparison:toggle' object.id %}"
        data-role="comparison-button"
        data-active="{% if object.id|is_compared:request %}true{% else %}false{% endif %}"
        class="{{ class }}">
    <i class="fa fa-exchange"
       title="Dodaj do porównania"
       style="display: none;"
       data-role="comparison-add"></i>
    <i class="fa fa-minus-square"
       title="Usuń z porównania"
       style="display: none;"
       data-role="comparison-remove"></i>
    <i class="fa fa-spinner fa-pulse" data-role="loading"></i>
</button>